# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hzj/Code/sandbox

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hzj/Code/sandbox

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hzj/Code/sandbox/CMakeFiles /home/hzj/Code/sandbox/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hzj/Code/sandbox/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sandbox.so

# Build rule for target.
sandbox.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sandbox.so
.PHONY : sandbox.so

# fast build rule for target.
sandbox.so/fast:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/build
.PHONY : sandbox.so/fast

src/child.o: src/child.cpp.o

.PHONY : src/child.o

# target to build an object file
src/child.cpp.o:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/child.cpp.o
.PHONY : src/child.cpp.o

src/child.i: src/child.cpp.i

.PHONY : src/child.i

# target to preprocess a source file
src/child.cpp.i:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/child.cpp.i
.PHONY : src/child.cpp.i

src/child.s: src/child.cpp.s

.PHONY : src/child.s

# target to generate assembly for a file
src/child.cpp.s:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/child.cpp.s
.PHONY : src/child.cpp.s

src/log.o: src/log.cpp.o

.PHONY : src/log.o

# target to build an object file
src/log.cpp.o:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/log.cpp.o
.PHONY : src/log.cpp.o

src/log.i: src/log.cpp.i

.PHONY : src/log.i

# target to preprocess a source file
src/log.cpp.i:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/log.cpp.i
.PHONY : src/log.cpp.i

src/log.s: src/log.cpp.s

.PHONY : src/log.s

# target to generate assembly for a file
src/log.cpp.s:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/log.cpp.s
.PHONY : src/log.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/runner.o: src/runner.cpp.o

.PHONY : src/runner.o

# target to build an object file
src/runner.cpp.o:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/runner.cpp.o
.PHONY : src/runner.cpp.o

src/runner.i: src/runner.cpp.i

.PHONY : src/runner.i

# target to preprocess a source file
src/runner.cpp.i:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/runner.cpp.i
.PHONY : src/runner.cpp.i

src/runner.s: src/runner.cpp.s

.PHONY : src/runner.s

# target to generate assembly for a file
src/runner.cpp.s:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/runner.cpp.s
.PHONY : src/runner.cpp.s

src/scmp/scmp.o: src/scmp/scmp.cpp.o

.PHONY : src/scmp/scmp.o

# target to build an object file
src/scmp/scmp.cpp.o:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/scmp.cpp.o
.PHONY : src/scmp/scmp.cpp.o

src/scmp/scmp.i: src/scmp/scmp.cpp.i

.PHONY : src/scmp/scmp.i

# target to preprocess a source file
src/scmp/scmp.cpp.i:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/scmp.cpp.i
.PHONY : src/scmp/scmp.cpp.i

src/scmp/scmp.s: src/scmp/scmp.cpp.s

.PHONY : src/scmp/scmp.s

# target to generate assembly for a file
src/scmp/scmp.cpp.s:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/scmp.cpp.s
.PHONY : src/scmp/scmp.cpp.s

src/scmp/scmp_gentle.o: src/scmp/scmp_gentle.cpp.o

.PHONY : src/scmp/scmp_gentle.o

# target to build an object file
src/scmp/scmp_gentle.cpp.o:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/scmp_gentle.cpp.o
.PHONY : src/scmp/scmp_gentle.cpp.o

src/scmp/scmp_gentle.i: src/scmp/scmp_gentle.cpp.i

.PHONY : src/scmp/scmp_gentle.i

# target to preprocess a source file
src/scmp/scmp_gentle.cpp.i:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/scmp_gentle.cpp.i
.PHONY : src/scmp/scmp_gentle.cpp.i

src/scmp/scmp_gentle.s: src/scmp/scmp_gentle.cpp.s

.PHONY : src/scmp/scmp_gentle.s

# target to generate assembly for a file
src/scmp/scmp_gentle.cpp.s:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/scmp_gentle.cpp.s
.PHONY : src/scmp/scmp_gentle.cpp.s

src/scmp/scmp_strict.o: src/scmp/scmp_strict.cpp.o

.PHONY : src/scmp/scmp_strict.o

# target to build an object file
src/scmp/scmp_strict.cpp.o:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/scmp_strict.cpp.o
.PHONY : src/scmp/scmp_strict.cpp.o

src/scmp/scmp_strict.i: src/scmp/scmp_strict.cpp.i

.PHONY : src/scmp/scmp_strict.i

# target to preprocess a source file
src/scmp/scmp_strict.cpp.i:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/scmp_strict.cpp.i
.PHONY : src/scmp/scmp_strict.cpp.i

src/scmp/scmp_strict.s: src/scmp/scmp_strict.cpp.s

.PHONY : src/scmp/scmp_strict.s

# target to generate assembly for a file
src/scmp/scmp_strict.cpp.s:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/scmp_strict.cpp.s
.PHONY : src/scmp/scmp_strict.cpp.s

src/scmp/semp_compile.o: src/scmp/semp_compile.cpp.o

.PHONY : src/scmp/semp_compile.o

# target to build an object file
src/scmp/semp_compile.cpp.o:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/semp_compile.cpp.o
.PHONY : src/scmp/semp_compile.cpp.o

src/scmp/semp_compile.i: src/scmp/semp_compile.cpp.i

.PHONY : src/scmp/semp_compile.i

# target to preprocess a source file
src/scmp/semp_compile.cpp.i:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/semp_compile.cpp.i
.PHONY : src/scmp/semp_compile.cpp.i

src/scmp/semp_compile.s: src/scmp/semp_compile.cpp.s

.PHONY : src/scmp/semp_compile.s

# target to generate assembly for a file
src/scmp/semp_compile.cpp.s:
	$(MAKE) -f CMakeFiles/sandbox.so.dir/build.make CMakeFiles/sandbox.so.dir/src/scmp/semp_compile.cpp.s
.PHONY : src/scmp/semp_compile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sandbox.so"
	@echo "... test"
	@echo "... src/child.o"
	@echo "... src/child.i"
	@echo "... src/child.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/runner.o"
	@echo "... src/runner.i"
	@echo "... src/runner.s"
	@echo "... src/scmp/scmp.o"
	@echo "... src/scmp/scmp.i"
	@echo "... src/scmp/scmp.s"
	@echo "... src/scmp/scmp_gentle.o"
	@echo "... src/scmp/scmp_gentle.i"
	@echo "... src/scmp/scmp_gentle.s"
	@echo "... src/scmp/scmp_strict.o"
	@echo "... src/scmp/scmp_strict.i"
	@echo "... src/scmp/scmp_strict.s"
	@echo "... src/scmp/semp_compile.o"
	@echo "... src/scmp/semp_compile.i"
	@echo "... src/scmp/semp_compile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

